use_frameworks!

platform :ios, '10.0'

target 'Venuz_Example' do
  pod 'Venuz', :path => '../'

  target 'Venuz_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
